### GET LISTAR
 
GET http://localhost:8080/users


### GET with invalid ID

GET http://localhost:8080/users/613e7127fc6ca918df35b69f


### POST new User - CRIAR

POST http://localhost:8080/users
Content-Type: application/json

{
    "name": "John Doe",
    "password": "senhaAleatoriaQualquer123",
    "email": "john.doe@newtonpaiva.br",
    "mobile": "+55(31)99134-5421",
    "status": "INACTIVE",
    "role": "ADMIN"
}

### POST new User - CRIAR

POST http://localhost:8080/users
Content-Type: application/json

{
    "name": "Daniel Rabelo",
    "password": "senhaAleeqweqtoriaQualquer123",
    "email": "danielRABELO@newtonpaiva.br",
    "mobile": "+55(31)99534-5728",
    "status": "ACTIVE",
    "role": "READ"
}

### PUT update user - ATUALIZAR se atualizar oq n existe erro 404

PUT http://localhost:8080/users/613fdfccdc4d7f6ba40befbc
Content-Type: application/json

{
    "name": "Diego Rafael",
    "password": "senhaAleatoriaQualquer11231243",
    "email": "danielrabelo@newtonpaiva.br",
    "mobile": "+55(31)52134-5451",
    "status": "BLOCKED",
    "role": "MODIFY"
}

### DELETE  - DELETAR se deletar oq n existe erro 404

DELETE http://localhost:8080/users/613fdfdadc4d7f6ba40befbd







############# E M P L O Y E E ##############

### GET LISTAR
 
GET http://localhost:8080/employees


### GET with invalid ID

GET http://localhost:8080/employees/613e7127fc6ca918df35b69f


### POST new User - CRIAR

POST http://localhost:8080/employees
Content-Type: application/json

{
    "firstName": "Daniel",
    "lastName": "Rabelo",
    "position": "Contagem",
    "gender": "MASC",
    "monthlySalary": "123.66",
    "hourSalary": "1500.00",
    "area": "Analista de Sistema"
}

### POST new User - CRIAR

POST http://localhost:8080/employees
Content-Type: application/json

{
    "firstName": "Cristiana",
    "lastName": "Rodrigues",
    "position": "Lisboa",
    "gender": "FEM",
    "monthlySalary": "823.66",
    "hourSalary": "5000.00",
    "area": "Engenharia"
}


### PUT update user - ATUALIZAR se atualizar oq n existe erro 404

PUT http://localhost:8080/employees/613fdd2b56c90f79d982f5e9
Content-Type: application/json

{
    "firstName": "Diego",
    "lastName": "Rafael",
    "position": "Contagem",
    "gender": "MASC",
    "monthlySalary": "500.66",
    "hourSalary": "6500.00",
    "area": "Advogado"
}


### DELETE  - DELETAR se deletar oq n existe erro 404

DELETE http://localhost:8080/employees/613fdd2c56c90f79d982f5ea